### ISSUE TITLE
installation on Apple Mac 

### ISSUE THREAD

**Issue by carbonmetrics** [qmd-lab/closeread#144]
When trying to compile 

```
---
title: My First Closeread
format: closeread-html
---
Hello world! 
```

I get

```
> $ quarto preview /Users/henk.harmsen/Desktop/test.qmd --no-browser --no-watch-inputs                                                                                                                                                                      [±main ●]
ERROR: Unable to read the extension 'closeread'.
Please ensure that you provided the correct id and that the extension is installed.

Stack trace:
Please ensure that you provided the correct id and that the extension is installed.
    at loadExtension (file:///Applications/quarto/bin/quarto.js:42891:15)
    at Object.extension (file:///Applications/quarto/bin/quarto.js:42789:34)
    at readExtensionFormat (file:///Applications/quarto/bin/quarto.js:73141:50)
    at resolveFormats (file:///Applications/quarto/bin/quarto.js:73085:41)
    at async renderContexts (file:///Applications/quarto/bin/quarto.js:72910:21)
    at async renderFormats (file:///Applications/quarto/bin/quarto.js:72954:22)
    at async file:///Applications/quarto/bin/quarto.js:100724:24
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:100721:25)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8017:13)
    at async Command.parseCommand (file:///Applications/quarto/bin/quarto.js:7907:20)
```

quarto environment:

[> $ quarto check                                                                                                                                 [±main ●]
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
      Jupyter: 5.7.2
      Kernels: python3, SageMath-10.4

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

henk.harmsen@henkharmsens-macbook-air ~/Documents/internal/case-book                                                                            [11:35:48]
> $ quarto add qmd-lab/closeread                                                                                                                 [±main ●]

Quarto extensions may execute code when documents are rendered. If you do not
trust the authors of the extension, we recommend that you do not install or
use the extension.
? Do you trust the authors of this extension (Y/n) › Yes
[✓] Downloading
[✓] Unzipping
    Found 1 extension.

The following changes will be made:
closeread   [No Change]    (format)
? Would you like to continue (Y/n) › Yes

[✓] Copying
[✓] Extension installation complete

? View documentation using default browser? (Y/n) › No](url)

**Comment by jimjam-slam** [comment]
> found that you must repeat the 
> 
> 
> 
> `quarto add qmd-lab/closeread`
> 
> 
> 
> for every single folder where you plan to run closeread;
> 
> it's not a global installation.

Hi @carbonmetrics! Yes, as you've found, you need to add Quarto extensions to every project (or document, if you render single documents without projects) individually — there's no global install option like npm's.
